export const EAP_TEXTS = {
  biology:{title:"Cellular Signalling and Gene Regulation",level:"Academic Biology",passage:`Cellular signalling pathways translate external stimuli into precise intracellular responses through cascades of molecular interactions. When a ligand binds to a membrane receptor, it induces conformational changes that activate downstream effectors, ultimately modulating gene expression in the nucleus. The specificity of these responses depends not merely on the identity of the ligand but on the cellular context — the complement of receptors expressed, the availability of second messengers, and the chromatin state of target genes. Dysregulation of signalling cascades is implicated in the pathogenesis of numerous diseases, including cancer, diabetes, and autoimmune disorders. Therapeutic strategies increasingly target specific nodes within these pathways, seeking to restore homeostatic balance without disrupting essential physiological functions.`},
  physics:{title:"Quantum Decoherence and Classical Emergence",level:"Academic Physics",passage:`Quantum decoherence provides the most compelling explanation for the emergence of classical behaviour from quantum mechanical foundations. When a quantum system interacts with its environment, the phase relationships between its superposed states are rapidly destroyed through entanglement with environmental degrees of freedom. This process, occurring on timescales far shorter than those accessible to measurement, effectively suppresses quantum interference and produces the appearance of definite classical outcomes. Decoherence does not, however, solve the measurement problem in its entirety; it explains why we observe classical statistics without resolving why any particular outcome is realised. The decoherence programme has nonetheless transformed our understanding of the quantum-to-classical transition and informs the engineering challenges confronting quantum computing architectures.`},
  cs:{title:"Distributed Systems and Fault Tolerance",level:"Academic Computer Science",passage:`Distributed systems achieve fault tolerance through redundancy, replication, and consensus protocols that maintain consistency despite partial failures. The CAP theorem establishes a fundamental trilemma: no distributed system can simultaneously guarantee consistency, availability, and partition tolerance when network partitions occur. Practical systems navigate this constraint by selectively relaxing one property under failure conditions — typically sacrificing strong consistency in favour of availability and partition tolerance. Modern distributed databases employ eventual consistency models, in which replicas converge to the same state given sufficient time and absence of further updates. The engineering challenge lies in quantifying and bounding inconsistency windows, and in designing application logic that tolerates temporary divergence without compromising correctness at the system level.`},
  mathematics:{title:"Measure Theory and Probability",level:"Academic Mathematics",passage:`Measure theory provides the rigorous foundation upon which modern probability theory is constructed. A probability space consists of a sample space, a sigma-algebra of measurable events, and a probability measure assigning values in the unit interval to events in a manner consistent with countable additivity. This framework resolves the paradoxes that plagued earlier frequency-based approaches and accommodates continuous probability distributions without recourse to infinitesimals. The Lebesgue integral, defined with respect to an arbitrary measure, generalises the Riemann integral and permits the interchange of limits and integrals under far weaker conditions. These technical advances are not merely foundational; they underpin the rigorous treatment of stochastic processes, martingale theory, and the mathematical analysis of financial derivatives.`},
  chemistry:{title:"Reaction Mechanisms and Transition States",level:"Academic Chemistry",passage:`Organic reaction mechanisms describe the stepwise sequence of bond-breaking and bond-forming events through which reactants are converted to products. Each elementary step proceeds through a transition state — a high-energy configuration at the saddle point of the potential energy surface — whose structure and energy determine the rate of the reaction. Nucleophilic substitution reactions illustrate how mechanism depends critically on substrate structure and reaction conditions: SN2 reactions proceed via a concerted backside attack with inversion of configuration, while SN1 reactions involve prior ionisation to a carbocation intermediate. The Hammond postulate relates transition state structure to the thermodynamic stability of adjacent species, providing a conceptual bridge between kinetic and thermodynamic perspectives. Computational chemistry now enables the direct calculation of transition state geometries and activation energies with quantitative accuracy.`},
  engineering:{title:"Structural Dynamics and Seismic Response",level:"Academic Engineering",passage:`Structural dynamics analyses the response of built systems to time-varying loads, with particular attention to resonance phenomena and energy dissipation mechanisms. Every structure possesses natural frequencies at which it oscillates freely following an impulse; when external forcing frequencies approach these natural frequencies, response amplitudes increase dramatically — a phenomenon exploited in some applications but catastrophic in others. Seismic design codes require that structures either resist earthquake-induced forces elastically or dissipate energy through controlled inelastic deformation, avoiding brittle failure modes. Modern performance-based earthquake engineering specifies acceptable damage states across a range of seismic hazard levels, moving beyond binary safe/unsafe assessments. Base isolation systems and tuned mass dampers represent passive control strategies that modify a structure's dynamic properties without requiring active intervention.`},
  design:{title:"Spatial Cognition and Environmental Psychology",level:"Academic Architecture & Design",passage:`Environmental psychology investigates how physical settings influence human cognition, emotion, and behaviour — questions of direct relevance to architectural and interior design practice. Spatial cognition research demonstrates that people construct mental maps of environments through a combination of landmark recognition, route knowledge, and survey understanding, with individual differences in spatial ability mediating the ease and accuracy of this process. Legibility — the degree to which an environment can be understood and navigated — emerges from the clarity of spatial structure, the distinctiveness of landmarks, and the coherence of visual sequences. Evidence consistently links high legibility to reduced stress, improved wayfinding performance, and greater environmental satisfaction. These findings have practical implications for the design of hospitals, airports, and urban districts, where disorientation carries significant functional and psychological costs.`},
};

export const EAP_QUESTIONS = {
biology:[
  {id:"bio_r1",type:"reading",q:"According to the passage, the specificity of cellular signalling responses depends on:",opts:["The concentration of the ligand alone","The identity of the ligand and the cellular context","The speed of the conformational change","The number of membrane receptors expressed"],correct:1,exp:"The passage states specificity depends 'not merely on the identity of the ligand but on the cellular context'."},
  {id:"bio_r2",type:"reading",q:"What do therapeutic strategies increasingly aim to do?",opts:["Eliminate all signalling pathways","Replace damaged receptors","Target specific nodes to restore homeostatic balance","Block all ligand-receptor interactions"],correct:2,exp:"The passage states strategies 'target specific nodes within these pathways, seeking to restore homeostatic balance'."},
  {id:"bio_r3",type:"reading",q:"Which diseases does the passage link to dysregulation of signalling cascades?",opts:["Malaria, tuberculosis, and HIV","Cancer, diabetes, and autoimmune disorders","Alzheimer's and Parkinson's disease","Heart disease and stroke only"],correct:1,exp:"The passage explicitly names 'cancer, diabetes, and autoimmune disorders'."},
  {id:"bio_r4",type:"reading",q:"What role does chromatin state play according to the passage?",opts:["It determines ligand concentration","It is part of the cellular context affecting response specificity","It directly activates second messengers","It forms the membrane receptor structure"],correct:1,exp:"Chromatin state is listed as one component of 'cellular context' affecting signalling specificity."},
  {id:"bio_r5",type:"reading",q:"The passage primarily argues that:",opts:["Cellular signalling is too complex to treat","Understanding signalling context is essential for disease treatment","All diseases are caused by receptor malfunction","Gene expression cannot be modulated externally"],correct:1,exp:"The passage moves from mechanism to disease implication to therapeutic strategy."},
  {id:"bio_v1",type:"vocabulary",q:"In the passage, 'cascades' most closely means:",opts:["Waterfalls in a laboratory","Sequential chains of molecular reactions","Simultaneous parallel processes","Random chemical events"],correct:1,exp:"'Cascades' = sequential chains where each step triggers the next."},
  {id:"bio_v2",type:"vocabulary",q:"'Modulating' in 'modulating gene expression' means:",opts:["Permanently silencing","Measuring with precision","Regulating or adjusting","Destroying completely"],correct:2,exp:"'Modulate' = regulate or adjust. French cognate: 'moduler'."},
  {id:"bio_v3",type:"vocabulary",q:"'Dysregulation' as used in the passage means:",opts:["Normal regulation","Abnormal or impaired regulatory function","The study of regulatory systems","Deliberate suppression"],correct:1,exp:"'Dys-' (Greek: bad/abnormal) + 'regulation' = abnormal or impaired function."},
  {id:"bio_v4",type:"vocabulary",q:"'Homeostatic' refers to:",opts:["A type of immune response","Relating to high-temperature processes","Maintaining stable internal conditions","The study of hormones"],correct:2,exp:"Homeostasis = maintaining stable internal conditions."},
  {id:"bio_v5",type:"vocabulary",q:"'Implicated' in the passage means:",opts:["Proven to cause directly","Shown to be involved or connected","Excluded from consideration","Studied without conclusion"],correct:1,exp:"'Implicated' = shown to be involved. From Latin 'implicare' (to entangle)."},
  {id:"bio_s1",type:"structure",q:"The overall structure of this passage is best described as:",opts:["A chronological account of a discovery","A problem followed by a proposed solution","An explanation of a mechanism leading to applications","A comparison of two competing theories"],correct:2,exp:"The passage explains how signalling works (mechanism), then moves to disease implications and therapeutic applications."},
  {id:"bio_s2",type:"structure",q:"The function of the final sentence is to:",opts:["Introduce a new unrelated topic","Show the practical relevance of the preceding science","Contradict the earlier claims","Summarise the entire passage"],correct:1,exp:"It closes the mechanism-to-application arc, showing why understanding signalling matters practically."},
  {id:"bio_s3",type:"structure",q:"The phrase 'not merely... but...' signals:",opts:["A simple list","A contrast that adds complexity to a previous claim","A direct contradiction","A definition"],correct:1,exp:"'Not merely X but Y' signals elaboration — moving from a simpler to a more complete explanation."},
  {id:"bio_c1",type:"calibration_pre",q:"Before answering, how confident were you that you would understand this biology text?",opts:["Not at all confident","Slightly confident","Moderately confident","Very confident"],correct:-1,exp:""},
  {id:"bio_c2",type:"calibration_post",q:"Having completed the questions, how well did you understand the passage overall?",opts:["Very poorly — I struggled throughout","Somewhat — main ideas but missed details","Well — I understood most of it","Very well — no difficulty"],correct:-1,exp:""},
],
physics:[
  {id:"phy_r1",type:"reading",q:"According to the passage, decoherence occurs because:",opts:["Measurement devices are imprecise","The quantum system entangles with its environment","Superposition states are inherently unstable","Observers disturb the system directly"],correct:1,exp:"The passage states decoherence occurs 'through entanglement with environmental degrees of freedom'."},
  {id:"phy_r2",type:"reading",q:"What limitation of decoherence does the passage acknowledge?",opts:["It cannot explain classical statistics","It is too slow to observe","It does not explain why a particular outcome is realised","It only applies to macroscopic systems"],correct:2,exp:"The passage: decoherence 'does not solve the measurement problem' — it doesn't explain why one specific outcome occurs."},
  {id:"phy_r3",type:"reading",q:"On what timescale does decoherence occur?",opts:["Timescales accessible to measurement","Timescales far shorter than those accessible to measurement","Timescales of seconds to minutes","Geological timescales"],correct:1,exp:"The passage states decoherence occurs 'on timescales far shorter than those accessible to measurement'."},
  {id:"phy_r4",type:"reading",q:"The passage claims decoherence has practical implications for:",opts:["Nuclear power plant design","Gravitational wave detection","Quantum computing architectures","Optical telescope construction"],correct:2,exp:"The passage: decoherence 'informs the engineering challenges confronting quantum computing architectures'."},
  {id:"phy_r5",type:"reading",q:"The main claim of this passage is that:",opts:["Quantum mechanics is incompatible with classical physics","Decoherence explains classical emergence but incompletely solves the measurement problem","Measurement is impossible at the quantum scale","Superposition states are permanent"],correct:1,exp:"The passage presents decoherence as the best explanation while honestly noting its limits."},
  {id:"phy_v1",type:"vocabulary",q:"'Superposed' in 'superposed states' most likely means:",opts:["Destroyed or eliminated","Existing in multiple states simultaneously","Measured with high precision","Arranged in a physical stack"],correct:1,exp:"Superposition in quantum mechanics = existing in multiple states simultaneously until measured."},
  {id:"phy_v2",type:"vocabulary",q:"'Suppresses' in 'suppresses quantum interference' means:",opts:["Amplifies or increases","Measures or records","Reduces or prevents","Predicts or forecasts"],correct:2,exp:"'Suppress' = reduce or prevent. French: 'supprimer'."},
  {id:"phy_v3",type:"vocabulary",q:"'Compelling' as used in 'most compelling explanation' means:",opts:["Complicated and confusing","Forcefully convincing","Recently proposed","Mathematically simple"],correct:1,exp:"'Compelling' = powerfully convincing. From Latin 'compellere'."},
  {id:"phy_v4",type:"vocabulary",q:"'Confronting' in 'challenges confronting quantum computing' means:",opts:["Solving problems effectively","Facing or dealing with difficulties","Designing new systems","Measuring quantum states"],correct:1,exp:"'Confronting challenges' = facing or dealing with difficulties."},
  {id:"phy_v5",type:"vocabulary",q:"'Transformed' in 'transformed our understanding' suggests:",opts:["Slightly adjusted","Fundamentally changed","Mathematically proven","Temporarily shifted"],correct:1,exp:"'Transform' = fundamentally change — stronger than 'modify' or 'adjust'."},
  {id:"phy_s1",type:"structure",q:"The passage is structured as:",opts:["A historical narrative","An explanation of decoherence, its limits, and its significance","A set of instructions for quantum computing","A comparison of quantum and classical experiments"],correct:1,exp:"The passage: explains the mechanism → acknowledges a limitation → states broader significance."},
  {id:"phy_s2",type:"structure",q:"'Nonetheless' in the final sentence signals:",opts:["A contradiction","A continuation despite an acknowledged limitation","A definition","A summary"],correct:1,exp:"'Nonetheless' = despite the limitation just mentioned, the conclusion still holds — a concessive move."},
  {id:"phy_s3",type:"structure",q:"The sentence beginning 'Decoherence does not, however...' serves to:",opts:["Introduce the main argument","Qualify the previous claim by acknowledging a limitation","Provide a definition","Describe an experiment"],correct:1,exp:"'However' signals a qualification — the author acknowledges the limits of the theory just explained."},
  {id:"phy_c1",type:"calibration_pre",q:"Before answering, how confident were you that you would understand this physics text?",opts:["Not at all confident","Slightly confident","Moderately confident","Very confident"],correct:-1,exp:""},
  {id:"phy_c2",type:"calibration_post",q:"Having completed the questions, how well did you understand the passage overall?",opts:["Very poorly — I struggled throughout","Somewhat — main ideas but missed details","Well — I understood most of it","Very well — no difficulty"],correct:-1,exp:""},
],
cs:[
  {id:"cs_r1",type:"reading",q:"According to the CAP theorem, what cannot be simultaneously guaranteed?",opts:["Speed, security, and scalability","Consistency, availability, and partition tolerance","Redundancy, replication, and consensus","Fault tolerance, efficiency, and correctness"],correct:1,exp:"The passage: 'no distributed system can simultaneously guarantee consistency, availability, and partition tolerance'."},
  {id:"cs_r2",type:"reading",q:"How do practical systems navigate the CAP constraint?",opts:["By eliminating network partitions","By sacrificing strong consistency for availability and partition tolerance","By prioritising consistency over all other properties","By using centralised control"],correct:1,exp:"The passage states systems 'typically sacrific[e] strong consistency in favour of availability and partition tolerance'."},
  {id:"cs_r3",type:"reading",q:"In eventual consistency models, replicas:",opts:["Are always identical","Converge to the same state given time and no further updates","Are permanently isolated","Reject conflicting updates automatically"],correct:1,exp:"The passage: 'replicas converge to the same state given sufficient time and absence of further updates'."},
  {id:"cs_r4",type:"reading",q:"The engineering challenge described in the final sentence involves:",opts:["Designing faster hardware","Bounding inconsistency windows and tolerating temporary divergence","Replacing consensus protocols","Eliminating replication"],correct:1,exp:"The passage identifies 'quantifying and bounding inconsistency windows' and designing tolerant application logic."},
  {id:"cs_r5",type:"reading",q:"The passage primarily serves to:",opts:["Argue that distributed systems are fundamentally flawed","Explain a fundamental constraint and how engineers work around it","Compare specific database products","Provide a historical account"],correct:1,exp:"The passage presents the CAP theorem (constraint) and describes how real systems navigate it."},
  {id:"cs_v1",type:"vocabulary",q:"'Trilemma' as used in the passage means:",opts:["A three-part solution","A situation with three mutually exclusive desirable properties","A mathematical theorem with three variables","A type of network architecture"],correct:1,exp:"A trilemma = three desirable properties that cannot all be achieved simultaneously."},
  {id:"cs_v2",type:"vocabulary",q:"'Selectively relaxing' a property means:",opts:["Completely eliminating it","Choosing to weaken it under specific conditions","Measuring it more carefully","Replacing it with another property"],correct:1,exp:"'Selectively relax' = deliberately weaken one property under specific conditions while maintaining others."},
  {id:"cs_v3",type:"vocabulary",q:"'Divergence' in 'tolerating temporary divergence' refers to:",opts:["Network speed differences","Replicas having temporarily different states","Programming language incompatibilities","Hardware failures"],correct:1,exp:"Divergence = replicas being temporarily out of sync — holding different values for the same data."},
  {id:"cs_v4",type:"vocabulary",q:"'Correctness' at the system level means:",opts:["The system runs without errors","Results consistent with the system's specification","The code has no syntax errors","The hardware operates at full speed"],correct:1,exp:"'Correctness' = the system behaves according to its formal specification, even under failures."},
  {id:"cs_v5",type:"vocabulary",q:"'Partial failures' refers to:",opts:["Failures affecting only part of a program","Some nodes failing while others continue","Incomplete data transmission","Software bugs affecting certain operations"],correct:1,exp:"In distributed systems, 'partial failure' = some nodes failing while the rest of the system continues."},
  {id:"cs_s1",type:"structure",q:"The passage moves from:",opts:["Specific examples to general principles","General principles to specific engineering challenges","Historical context to current research","Problem definition to problem solution"],correct:3,exp:"The passage: defines the problem → states the theoretical constraint (CAP) → describes engineering responses → identifies remaining challenges."},
  {id:"cs_s2",type:"structure",q:"'Practical systems navigate this constraint' signals:",opts:["A contradiction of the CAP theorem","A shift from theoretical constraint to practical response","A new definition","The end of the argument"],correct:1,exp:"This marks the transition from theory (CAP theorem) to practice (how engineers actually respond)."},
  {id:"cs_s3",type:"structure",q:"'The engineering challenge lies in...' functions to:",opts:["Summarise the CAP theorem","Introduce a contradiction","Identify the open problem that practitioners face","Define eventual consistency"],correct:2,exp:"After explaining the theory and current practice, it identifies what remains to be solved — the persistent challenge."},
  {id:"cs_c1",type:"calibration_pre",q:"Before answering, how confident were you that you would understand this computer science text?",opts:["Not at all confident","Slightly confident","Moderately confident","Very confident"],correct:-1,exp:""},
  {id:"cs_c2",type:"calibration_post",q:"Having completed the questions, how well did you understand the passage overall?",opts:["Very poorly — I struggled throughout","Somewhat — main ideas but missed details","Well — I understood most of it","Very well — no difficulty"],correct:-1,exp:""},
],
mathematics:[
  {id:"mat_r1",type:"reading",q:"A probability space consists of:",opts:["A sample space, a mean, and a standard deviation","A sample space, a sigma-algebra, and a probability measure","A set of random variables and their distributions","An experiment, its outcomes, and a histogram"],correct:1,exp:"The passage defines the three components explicitly."},
  {id:"mat_r2",type:"reading",q:"What problem does measure theory resolve?",opts:["The impossibility of calculating probabilities","Paradoxes that plagued earlier frequency-based approaches","The lack of a definition for random variables","The difficulty of computing Riemann integrals"],correct:1,exp:"The passage: measure theory 'resolves the paradoxes that plagued earlier frequency-based approaches'."},
  {id:"mat_r3",type:"reading",q:"The Lebesgue integral permits:",opts:["Faster numerical computation","Exchange of limits and integrals under weaker conditions","Exact calculation of all probabilities","Elimination of continuous distributions"],correct:1,exp:"The passage: it 'permits the interchange of limits and integrals under far weaker conditions'."},
  {id:"mat_r4",type:"reading",q:"Which applications depend on these mathematical advances?",opts:["Geometry, calculus, and number theory","Stochastic processes, martingale theory, and financial derivatives","Statistics, data science, and machine learning","Algebra, topology, and combinatorics"],correct:1,exp:"The passage explicitly names these three applications."},
  {id:"mat_r5",type:"reading",q:"The passage argues that the advances described are:",opts:["Only of historical interest","Purely theoretical","Both foundational and practically significant","Too abstract to apply to real problems"],correct:2,exp:"The passage: 'These technical advances are not merely foundational' — they have direct practical applications."},
  {id:"mat_v1",type:"vocabulary",q:"'Rigorous' in 'rigorous foundation' means:",opts:["Complex and difficult","Based on intuition","Mathematically precise and free from logical gaps","Restricted to simple cases"],correct:2,exp:"'Rigorous' = mathematically precise, with every step formally justified. French: 'rigoureux'."},
  {id:"mat_v2",type:"vocabulary",q:"'Accommodates' in 'accommodates continuous probability distributions' means:",opts:["Rejects or excludes","Approximates with difficulty","Includes or handles naturally","Converts into discrete form"],correct:2,exp:"'Accommodate' = include or handle — measure theory naturally includes continuous distributions."},
  {id:"mat_v3",type:"vocabulary",q:"'Recourse' in 'without recourse to infinitesimals' means:",opts:["Reference or appeal to","Rejection of","Calculation using","Definition of"],correct:0,exp:"'Without recourse to X' = without needing to use or appeal to X."},
  {id:"mat_v4",type:"vocabulary",q:"'Underpins' in 'they underpin the rigorous treatment' means:",opts:["Contradicts or challenges","Forms the foundation or basis of","Is derived from","Replaces or supersedes"],correct:1,exp:"'Underpin' = form the foundation of, support from below."},
  {id:"mat_v5",type:"vocabulary",q:"'Countable additivity' refers to:",opts:["Adding any finite set of numbers","A property where probabilities of countably many disjoint events sum correctly","The ability to count all outcomes","A method for approximating integrals"],correct:1,exp:"Countable additivity = the probability of a countable union of disjoint events equals the sum of individual probabilities."},
  {id:"mat_s1",type:"structure",q:"The structure of this passage is best described as:",opts:["A step-by-step proof","A progression from foundational definition to practical significance","A comparison of two integrals","A historical account"],correct:1,exp:"The passage: defines the probability space → explains what it resolves → introduces the Lebesgue integral → states practical applications."},
  {id:"mat_s2",type:"structure",q:"'These technical advances are not merely foundational' signals:",opts:["A qualification reducing importance","An extension showing practical value beyond theory","A contradiction of the earlier argument","A summary of the main theorem"],correct:1,exp:"'Not merely X, they also Y' = a classic academic move extending significance beyond what was just claimed."},
  {id:"mat_s3",type:"structure",q:"'Without recourse to' functions to:",opts:["Introduce an alternative method","Specify a limitation","Highlight an advantage — achieving something without a problematic tool","Define a technical term"],correct:2,exp:"'Without recourse to infinitesimals' highlights that measure theory achieves its goals without their conceptual problems."},
  {id:"mat_c1",type:"calibration_pre",q:"Before answering, how confident were you that you would understand this mathematics text?",opts:["Not at all confident","Slightly confident","Moderately confident","Very confident"],correct:-1,exp:""},
  {id:"mat_c2",type:"calibration_post",q:"Having completed the questions, how well did you understand the passage overall?",opts:["Very poorly — I struggled throughout","Somewhat — main ideas but missed details","Well — I understood most of it","Very well — no difficulty"],correct:-1,exp:""},
],
chemistry:[
  {id:"che_r1",type:"reading",q:"What determines the rate of a reaction according to the passage?",opts:["The concentration of reactants only","The temperature and pressure","The structure and energy of the transition state","The identity of the solvent"],correct:2,exp:"The passage: the transition state's 'structure and energy determine the rate of the reaction'."},
  {id:"che_r2",type:"reading",q:"How does an SN2 reaction proceed?",opts:["Via prior ionisation to a carbocation","Through a concerted backside attack with inversion of configuration","By a radical mechanism","Through a two-step process with retention of configuration"],correct:1,exp:"The passage explicitly describes SN2 as 'a concerted backside attack with inversion of configuration'."},
  {id:"che_r3",type:"reading",q:"What does the Hammond postulate connect?",opts:["Kinetic and thermodynamic perspectives","Reactant concentration and product yield","Temperature and reaction rate","Molecular structure and physical properties"],correct:0,exp:"The passage: it 'provides a conceptual bridge between kinetic and thermodynamic perspectives'."},
  {id:"che_r4",type:"reading",q:"What advantage does computational chemistry offer?",opts:["It eliminates laboratory experiments","It enables calculation of transition state geometries and activation energies","It predicts reaction outcomes with certainty","It replaces mechanistic understanding"],correct:1,exp:"The passage: computation 'enables the direct calculation of transition state geometries and activation energies with quantitative accuracy'."},
  {id:"che_r5",type:"reading",q:"The SN1/SN2 contrast illustrates that:",opts:["All substitution reactions follow the same mechanism","Mechanism depends on substrate structure and reaction conditions","Temperature is the only factor determining mechanism","Carbocations are always intermediates"],correct:1,exp:"The passage: this 'illustrate[s] how mechanism depends critically on substrate structure and reaction conditions'."},
  {id:"che_v1",type:"vocabulary",q:"'Concerted' in 'concerted backside attack' means:",opts:["Performed carefully and slowly","Occurring in a single step without a discrete intermediate","Requiring a catalyst","Proceeding via a charged intermediate"],correct:1,exp:"'Concerted' = all bond changes occurring simultaneously — no intermediate exists."},
  {id:"che_v2",type:"vocabulary",q:"'Transition state' refers to:",opts:["The final product","The starting material","The highest-energy configuration that reactants must pass through","A stable intermediate"],correct:2,exp:"Transition state = the highest-energy point on the reaction coordinate — not an isolable intermediate."},
  {id:"che_v3",type:"vocabulary",q:"'Activation energy' means:",opts:["The energy released during a reaction","The minimum energy required for a reaction to proceed","The total energy of all reactants","The energy difference between products and reactants"],correct:1,exp:"Activation energy = the energy barrier that must be overcome — energy difference between reactants and the transition state."},
  {id:"che_v4",type:"vocabulary",q:"'Quantitative accuracy' means:",opts:["Approximate or estimated results","Qualitative predictions","Numerically precise, measurable results","Results that describe but do not measure"],correct:2,exp:"'Quantitative' = expressed in numbers, measurable. From Latin 'quantitas'. Contrasts with 'qualitative'."},
  {id:"che_v5",type:"vocabulary",q:"'Stepwise' means:",opts:["Random and unpredictable","Occurring all at once","Proceeding through discrete sequential stages","Requiring external energy at each stage"],correct:2,exp:"'Stepwise' = proceeding through distinct, sequential stages that can be identified and studied separately."},
  {id:"che_s1",type:"structure",q:"The passage is primarily organised as:",opts:["A comparison of SN1 and SN2 only","A definition of mechanism followed by examples and theoretical tools","A historical account","Instructions for predicting reaction outcomes"],correct:1,exp:"The passage: defines mechanisms → explains transition states → uses SN1/SN2 as examples → introduces Hammond postulate → mentions computational tools."},
  {id:"che_s2",type:"structure",q:"The SN1 and SN2 examples are included to:",opts:["Prove SN2 reactions are more useful","Illustrate that mechanism depends on structure and conditions","Define nucleophilic substitution","Compare the rates of two reactions"],correct:1,exp:"They function as concrete examples illustrating the abstract claim about mechanism dependence."},
  {id:"che_s3",type:"structure",q:"'Now enables' in the final sentence suggests:",opts:["This has always been possible","A recent development not previously achievable","A theoretical possibility only","It requires specialised equipment"],correct:1,exp:"'Now enables' signals a recent advance — contrasting current computational capability with what was possible before."},
  {id:"che_c1",type:"calibration_pre",q:"Before answering, how confident were you that you would understand this chemistry text?",opts:["Not at all confident","Slightly confident","Moderately confident","Very confident"],correct:-1,exp:""},
  {id:"che_c2",type:"calibration_post",q:"Having completed the questions, how well did you understand the passage overall?",opts:["Very poorly — I struggled throughout","Somewhat — main ideas but missed details","Well — I understood most of it","Very well — no difficulty"],correct:-1,exp:""},
],
engineering:[
  {id:"eng_r1",type:"reading",q:"What happens when external forcing frequencies approach natural frequencies?",opts:["The structure becomes more stable","Response amplitudes increase dramatically","Energy dissipation increases proportionally","The structure returns to rest immediately"],correct:1,exp:"The passage: 'response amplitudes increase dramatically — a phenomenon exploited in some applications but catastrophic in others'."},
  {id:"eng_r2",type:"reading",q:"How does performance-based earthquake engineering differ from earlier approaches?",opts:["It focuses only on preventing collapse","It uses simpler calculation methods","It specifies acceptable damage states across a range of hazard levels","It requires structures to remain elastic under all conditions"],correct:2,exp:"The passage: it 'specifies acceptable damage states across a range of seismic hazard levels, moving beyond binary safe/unsafe assessments'."},
  {id:"eng_r3",type:"reading",q:"Base isolation and tuned mass dampers are described as:",opts:["Active control strategies requiring sensors","Passive control strategies modifying dynamic properties","Structural elements providing additional stiffness","Emergency systems activated only during earthquakes"],correct:1,exp:"The passage: 'passive control strategies that modify a structure's dynamic properties without requiring active intervention'."},
  {id:"eng_r4",type:"reading",q:"Seismic design codes require structures to:",opts:["Be demolished and rebuilt after every earthquake","Either resist forces elastically or dissipate energy through inelastic deformation","Remain rigid and unbending","Use only base isolation systems"],correct:1,exp:"The passage: 'structures either resist earthquake-induced forces elastically or dissipate energy through controlled inelastic deformation'."},
  {id:"eng_r5",type:"reading",q:"The passage primarily aims to:",opts:["Argue that earthquakes cannot be designed for","Provide step-by-step seismic design instructions","Explain structural dynamics concepts and their seismic applications","Compare different types of damping systems"],correct:2,exp:"The passage moves from foundational concepts (natural frequencies, resonance) to applied seismic engineering."},
  {id:"eng_v1",type:"vocabulary",q:"'Resonance' in the passage refers to:",opts:["A type of structural material","Amplification of vibrations when forcing frequency matches natural frequency","The sound produced by a vibrating structure","Resistance to lateral loads"],correct:1,exp:"Resonance = dramatic amplification of response when the driving frequency matches the system's natural frequency."},
  {id:"eng_v2",type:"vocabulary",q:"'Inelastic deformation' implies:",opts:["The structure returns completely to its original shape","The structure deforms permanently","The structure fractures immediately","The structure vibrates without deforming"],correct:1,exp:"Inelastic = permanent deformation that does not recover when load is removed."},
  {id:"eng_v3",type:"vocabulary",q:"'Passive' in 'passive control strategies' means:",opts:["Strategies that fail under extreme loads","Control achieved without active sensing or power input","Strategies used only after earthquake damage","Approaches requiring continuous monitoring"],correct:1,exp:"Passive control = modifying structural properties without active sensors or energy input."},
  {id:"eng_v4",type:"vocabulary",q:"'Brittle failure' refers to:",opts:["Gradual, predictable deterioration","Sudden failure without significant prior deformation","Failure caused by corrosion","Elastic behaviour under extreme loads"],correct:1,exp:"Brittle failure = sudden, catastrophic failure without prior plastic deformation — gives no warning."},
  {id:"eng_v5",type:"vocabulary",q:"'Dissipate' in 'dissipate energy through controlled inelastic deformation' means:",opts:["Store energy for later use","Generate additional energy","Spread and absorb energy, converting it to heat","Transfer energy to adjacent structures"],correct:2,exp:"'Dissipate' = spread and absorb — energy is converted to heat through inelastic deformation."},
  {id:"eng_s1",type:"structure",q:"The passage is organised as:",opts:["A chronological history of earthquake engineering","Foundational concepts followed by their engineering applications","A comparison of passive and active control systems","A set of design rules"],correct:1,exp:"The passage: explains natural frequencies and resonance → applies to seismic design codes and performance-based engineering."},
  {id:"eng_s2",type:"structure",q:"'A phenomenon exploited in some applications but catastrophic in others' functions to:",opts:["Contradict the previous claim","Show that resonance is always beneficial","Acknowledge the dual nature of resonance — context-dependent","Define what resonance means"],correct:2,exp:"This phrase shows the author's nuanced view — resonance is not simply bad; context determines whether it's useful or destructive."},
  {id:"eng_s3",type:"structure",q:"'Moving beyond binary safe/unsafe assessments' signals:",opts:["A return to simpler methods","Progress from a coarser to a more nuanced approach","A rejection of seismic design","A new definition of structural safety"],correct:1,exp:"'Moving beyond' = progress. Performance-based engineering represents an advance over cruder binary assessments."},
  {id:"eng_c1",type:"calibration_pre",q:"Before answering, how confident were you that you would understand this engineering text?",opts:["Not at all confident","Slightly confident","Moderately confident","Very confident"],correct:-1,exp:""},
  {id:"eng_c2",type:"calibration_post",q:"Having completed the questions, how well did you understand the passage overall?",opts:["Very poorly — I struggled throughout","Somewhat — main ideas but missed details","Well — I understood most of it","Very well — no difficulty"],correct:-1,exp:""},
],
design:[
  {id:"des_r1",type:"reading",q:"Spatial cognition research shows that people construct mental maps through:",opts:["Visual memory alone","A combination of landmark recognition, route knowledge, and survey understanding","The use of maps and navigation aids","Following a single strategy"],correct:1,exp:"The passage: 'a combination of landmark recognition, route knowledge, and survey understanding'."},
  {id:"des_r2",type:"reading",q:"What does 'legibility' mean in this passage?",opts:["The clarity of text signs","The degree to which an environment can be understood and navigated","The aesthetic quality of a building","The brightness of interior lighting"],correct:1,exp:"The passage defines legibility as 'the degree to which an environment can be understood and navigated'."},
  {id:"des_r3",type:"reading",q:"High legibility is consistently linked to:",opts:["Higher construction costs","More complex forms","Reduced stress, improved wayfinding, and greater satisfaction","Greater visual stimulation"],correct:2,exp:"The passage: 'Evidence consistently links high legibility to reduced stress, improved wayfinding performance, and greater environmental satisfaction'."},
  {id:"des_r4",type:"reading",q:"Which building types does the passage specifically mention?",opts:["Museums, libraries, and galleries","Schools, offices, and factories","Hospitals, airports, and urban districts","Shopping centres, hotels, and sports venues"],correct:2,exp:"The passage explicitly names 'hospitals, airports, and urban districts'."},
  {id:"des_r5",type:"reading",q:"The passage argues that environmental psychology is relevant to design because:",opts:["It provides aesthetic guidelines","It shows how physical settings affect human cognition, emotion, and behaviour","It replaces subjective design decisions","It demonstrates all people respond identically to space"],correct:1,exp:"The passage opens by stating environmental psychology investigates 'questions of direct relevance to architectural and interior design practice'."},
  {id:"des_v1",type:"vocabulary",q:"'Mediating' in the passage means:",opts:["Eliminating or preventing","Measuring or recording","Influencing or moderating the relationship between factors","Directly causing the outcome"],correct:2,exp:"'Mediate' = act as an intermediary factor influencing the relationship between two other variables."},
  {id:"des_v2",type:"vocabulary",q:"'Legibility' in this architectural context is closest to:",opts:["Readability of written text","Comprehensibility of a space for navigation","Visual attractiveness of a facade","Transparency of glass walls"],correct:1,exp:"Legibility in spatial terms = comprehensibility — how well environments 'read' for navigation."},
  {id:"des_v3",type:"vocabulary",q:"'Coherence' in 'coherence of visual sequences' refers to:",opts:["Bright and colourful elements","A logical, consistent relationship between successive visual experiences","Many different and varied stimuli","The absence of visual boundaries"],correct:1,exp:"'Coherence' = logical consistency and connectedness — visual sequences that follow a comprehensible pattern."},
  {id:"des_v4",type:"vocabulary",q:"'Disorientation' as used means:",opts:["A state of heightened awareness","Confusion about one's location or direction","A preference for unusual spatial experiences","The inability to perceive light and shadow"],correct:1,exp:"'Disorientation' = confusion about where one is or which direction to go."},
  {id:"des_v5",type:"vocabulary",q:"'Survey understanding' of an environment most likely refers to:",opts:["Completing an official survey form","Understanding the environment from a bird's-eye, map-like perspective","Conducting interviews with building users","Measuring distances and dimensions"],correct:1,exp:"'Survey understanding' = a map-like, overhead mental representation of spatial layout — the most sophisticated level of spatial knowledge."},
  {id:"des_s1",type:"structure",q:"The passage moves from:",opts:["Specific buildings to general principles","General field definition to specific concept to practical implications","Historical examples to theoretical framework","Experimental results to design guidelines"],correct:1,exp:"The passage: introduces environmental psychology → defines spatial cognition and legibility → names practical applications."},
  {id:"des_s2",type:"structure",q:"'Evidence consistently links' signals:",opts:["A single study with uncertain results","A tentative hypothesis","A well-established finding supported by multiple sources","The author's personal opinion"],correct:2,exp:"'Evidence consistently links' = a well-supported finding across multiple studies."},
  {id:"des_s3",type:"structure",q:"The final sentence ('These findings have practical implications for...') functions to:",opts:["Introduce a new theoretical concept","Question the relevance of the research","Connect the research evidence to real-world design practice","Summarise the definition of legibility"],correct:2,exp:"This sentence bridges theory (research evidence) and practice (design applications)."},
  {id:"des_c1",type:"calibration_pre",q:"Before answering, how confident were you that you would understand this architecture and design text?",opts:["Not at all confident","Slightly confident","Moderately confident","Very confident"],correct:-1,exp:""},
  {id:"des_c2",type:"calibration_post",q:"Having completed the questions, how well did you understand the passage overall?",opts:["Very poorly — I struggled throughout","Somewhat — main ideas but missed details","Well — I understood most of it","Very well — no difficulty"],correct:-1,exp:""},
],
};

export const FIELD_TO_EAP={"Biology":"biology","Physics":"physics","Computer Science":"cs","Mathematics":"mathematics","Chemistry":"chemistry","Engineering":"engineering","Architecture & Design":"design","Other STEM":"biology"};
export const getEAPQuestions=(field)=>EAP_QUESTIONS[FIELD_TO_EAP[field]||"biology"]||EAP_QUESTIONS.biology;
export const getEAPText=(field)=>EAP_TEXTS[FIELD_TO_EAP[field]||"biology"]||EAP_TEXTS.biology;
export const scoreEAP=(questions,answers)=>{
  let reading=0,readingTotal=0,vocabulary=0,vocabularyTotal=0,structure=0,structureTotal=0,preCalib=null,postCalib=null;
  questions.forEach(q=>{
    const ans=answers[q.id];
    if(q.type==="reading"){readingTotal++;if(ans===q.correct)reading++;}
    else if(q.type==="vocabulary"){vocabularyTotal++;if(ans===q.correct)vocabulary++;}
    else if(q.type==="structure"){structureTotal++;if(ans===q.correct)structure++;}
    else if(q.type==="calibration_pre")preCalib=ans;
    else if(q.type==="calibration_post")postCalib=ans;
  });
  const total=reading+vocabulary+structure;
  const totalPossible=readingTotal+vocabularyTotal+structureTotal;
  return{total,totalPossible,reading,readingTotal,vocabulary,vocabularyTotal,structure,structureTotal,preCalib,postCalib,calibrationGap:(postCalib!==null&&preCalib!==null)?postCalib-preCalib:null,percentage:Math.round((total/totalPossible)*100)};
};
